from pathlib import Path

handover = Path("CURRENT_HANDOVER.md")
changelog = Path("CHANGELOG.md")

handover_anchor = "## AVR/HEOS network-path incident — 2 Sep 2026\n"
new_handover = """## AVR TCP/23 recurrence — 4 Sep 2026\n\nA second spontaneous `UNKNOWN` incident occurred during ordinary PHONO/vinyl listening, without voice/ReSpeaker activity. MarantzPi could still send source/volume commands, but no source was highlighted. Pi `/api/status` retained HEOS-side metadata but showed AVR state as `power:unknown`, `input:UNKNOWN`, `inputCode:UNKNOWN`, `volume:null`.\n\nThe live fault was preserved before recovery. From both Pi and HP, TCP connections to `192.168.50.220:23` succeeded but `SI?` returned zero bytes. HEOS port 1255 remained healthy and returned the SR8015 normally. The Pi Node poller showed two transient established TCP/23 sockets whose local ports changed across samples, demonstrating cycling/timeout behaviour rather than permanently stuck sockets. The HP held no persistent TCP/23 socket.\n\n`marantz-display.service` was then stopped and its TCP/23 sockets disappeared. Independent HP `SI?` probes remained silent after 10 seconds and again after more than one minute with zero Pi polling, so Pi polling is not required to maintain the wedged state. A passive 10-second TCP/23 listen also received no bytes.\n\nRecovery was isolated much more tightly than on 2 Sep: with the Pi display still stopped and the HP/network switch untouched, the SR8015 alone was put into normal standby, left for about 10 seconds, and powered back on. HP `SI?` immediately returned `SI8K\\r` (plus `SVOFF\\r`) and returned the same result again 10 seconds later. `SI8K` correctly matched the configured PHONO/Technics SL-1210G source. MarantzPi was then restarted and normal source display was confirmed.\n\nThis materially weakens the earlier suspicion of the external network switch and the ReSpeaker/voice path. Current evidence strongly localises the failure to the SR8015 or its internal network/control subsystem: TCP/23 accepts connections but becomes silent while HEOS remains healthy, and a normal AVR-only standby/on cycle can recover it. The exact trigger/root cause is still unproven. Do not claim a specific internal firmware/service defect without further evidence.\n\nFor a future recurrence, preserve the live fault first. The shortest proven diagnostic set is: raw `SI?` bytes from Pi and HP, HEOS 1255 health, Pi `/api/status`, and Pi/HP TCP/23 sockets. If those reproduce this exact signature, an AVR-only normal standby/on cycle is now the least-invasive proven recovery to try before network resets, host reboots or wall-power cycling.\n\n"""

changelog_anchor = "## 2026-09-02 — Personalised TIDAL PLAY FROM HERE\n"
new_changelog = """## 2026-09-04 — AVR TCP/23 recurrence isolated to AVR recovery\n\n- A second spontaneous `UNKNOWN` source/status failure occurred during ordinary PHONO/vinyl listening, without voice/ReSpeaker activity.\n- Both Pi and HP could establish TCP/23 connections to the SR8015 but received zero bytes for `SI?`; HEOS port 1255 remained healthy. Pi `/api/status` showed `power:unknown`, `input:UNKNOWN`, `inputCode:UNKNOWN` and `volume:null`.\n- Pi TCP/23 sockets were transient/cycling rather than permanently stuck. Stopping `marantz-display.service` removed all Pi TCP/23 activity, but independent HP queries remained silent after more than a minute, showing Pi polling was not required to maintain the fault.\n- With Pi polling still stopped, only the SR8015 was put into normal standby for about 10 seconds and powered back on. No HP, Pi or network-switch reboot/reset was performed.\n- AVR-only standby/on restored TCP/23 immediately and stably: repeated HP `SI?` probes returned `SI8K`, correctly identifying the configured PHONO/Technics input. MarantzPi was restarted and normal display operation was confirmed.\n- This materially weakens the 2 Sep external-switch and voice/ReSpeaker suspicions. Evidence now strongly localises the failure/recovery to the SR8015 or its internal network/control subsystem, but the trigger/root cause remains unproven.\n- For the same signature in future, preserve evidence first; AVR-only normal standby/on is now the least-invasive proven recovery before broader resets or cold power cycling.\n\n"""

for path, anchor, addition in ((handover, handover_anchor, new_handover), (changelog, changelog_anchor, new_changelog)):
    text = path.read_text()
    if text.count(anchor) != 1:
        raise SystemExit(f"guard failed for {path}: expected one anchor, found {text.count(anchor)}")
    if "AVR TCP/23 recurrence — 4 Sep 2026" in text or "2026-09-04 — AVR TCP/23 recurrence" in text:
        raise SystemExit(f"guard failed for {path}: recurrence documentation already present")
    path.write_text(text.replace(anchor, addition + anchor, 1))

print("Updated CURRENT_HANDOVER.md and CHANGELOG.md")
